# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='show_inhome',
            field=models.BooleanField(db_index=True, default=True, help_text='Used to control whether this entry show in home.', verbose_name='show in home?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pingback_enabled',
            field=models.BooleanField(default=False, help_text='Allows pingbacks if checked.', verbose_name='pingbacks enabled'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='trackback_enabled',
            field=models.BooleanField(default=False, help_text='Allows trackbacks if checked.', verbose_name='trackbacks enabled'),
        ),
    ]
